### ISSUE TITLE
Extend `oqm` with delete ops

### ISSUE THREAD

**Issue by bsnacks000** [cunybpl/aiodal#10]
Even though we usually do not need a delete command via REST we can use it for cases where we are not soft-deleting via patch and a true delete is not destructive. 

The current use case in bemadb is `projects <-> cpm` where we have M:M join without sensitive data linking these together.

**Comment by bsnacks000** [comment]
* `oqm.dbentity` 
    * Implement `Deletable` generic over FormData 

* `oqm.query` 
    * Implement `IDeleteQ` 
    * Implement `BaseDeleteQ` 
    * `DeleteQ`
* Create a new test module `test_oqm_deletable_dbentity` 

* In `test_oqm_crud_dbentity` incorporate the above into the mixed objects

**Comment by kgasiorowski** [comment]
Woops, wanted to start fresh and git accidentally closed the PR

**Comment by kgasiorowski** [comment]
Here's the updated PR

https://github.com/cunybpl/aiodal/pull/12
