### ISSUE TITLE
Mypy screaming

### ISSUE THREAD

**Issue by kgasiorowski** [cunybpl/aiodal#34]
`aiodal` is causing mypy to scream and explode in other projects, for example `meteodb`:

![image](https://github.com/cunybpl/aiodal/assets/12837328/070870cc-4be2-4cd2-abd3-c43e1dbc341d)

**Comment by bsnacks000** [comment]
![image](https://github.com/cunybpl/aiodal/assets/6597304/762bbce4-925e-4649-a1c6-af9627922fae)

**Comment by bsnacks000** [comment]
@tinnaing347 Would you mind taking a look at this after #39 ? I'm sure there is a way to get the stubs to work ... it is pretty annoying since we're using asyncpg directly more to have mypy lighting up the IDE while we're trying to write codes
