### ISSUE TITLE
Update libraries

### ISSUE THREAD

**Issue by bsnacks000** [cunybpl/aiodal#39]
@tinnaing347 Can we update all the core deps to the latest versions and check for any API breakages?

**Comment by tinnaing347** [comment]
We may be able to replace `python-jose` with `pyjwt` [link](https://github.com/jpadilla/pyjwt/tree/72ad55f6d7041ae698dc0790a690804118be50fc) instead. Also, `pyjwt` is sponsored by auth0.

**Comment by tinnaing347** [comment]
ref: https://auth0.com/blog/how-to-handle-jwt-in-python/

**Comment by bsnacks000** [comment]
Nice... yeah this is clearly more up to date and way less issues... Early next week maybe we can swap them out...

**Comment by tinnaing347** [comment]
@bsnacks000 added (or rather modified) e2e testing app for auth0; you will need to add secret `AUTH0_TESTING_CLIENT_SECRET` for gh action and run `e2e` marked tests.
